name: provider_with_clean_architecture
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  connectivity_plus: ^6.1.2
  dio: ^5.4.0
  equatable: ^2.0.5
  provider: ^6.1.1
  dartz: ^0.10.1
  get_it: ^8.0.3
  flutter_paypal: ^0.2.0
  url_launcher: ^6.2.3
  google_sign_in: ^6.1.6
  firebase_dynamic_links: ^6.1.1
  json_serializable: ^6.8.0
  freezed_annotation: ^2.4.4
  flutter_riverpod: ^2.5.1
  cherry_toast: ^1.11.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  font_awesome_flutter: ^10.0.0
  carousel_slider: ^5.0.0
  clipboard: ^0.1.3
  shimmer: ^3.0.0
  # flex_color_scheme: ^7.0.0
  # hive_ce: ^2.4.4
  # animations: ^2.0.11
  # archive: ^4.0.2
  # confetti: ^0.8.0
  # device_frame_plus: ^1.2.2+1
  # flex_color_picker: ^3.7.0
  # flex_seed_scheme: ^3.5.0
  # flutter_svg: ^2.0.16
  # google_fonts: ^6.2.1
  # intl: ^0.20.1
  # path_provider: ^2.1.5

  # string_scanner: ^1.3.0
  # web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  # flutter_lints: ^5.0.0
  path_provider: ^2.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
