name: provider_with_clean_architecture
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  connectivity_plus: ^3.0.2
  dio: ^5.4.0
  equatable: ^2.0.5
  provider: ^6.1.1
  dartz: ^0.10.1
  get_it: ^7.6.4
  flutter_paypal: ^0.2.0
  url_launcher: ^6.2.3
  google_sign_in: ^6.1.6
  firebase_core: ^2.24.2
  firebase_dynamic_links: ^5.4.8
  json_serializable: ^6.8.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  build_runner: ^2.4.11

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
