// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtGfX0TaVWl2atTVlftBDuNRKZE1hWHhk',
    appId: '1:234574443553:web:ee52863a2a5e589cdd9f60',
    messagingSenderId: '234574443553',
    projectId: 'deeplink-practice-nextstep',
    authDomain: 'deeplink-practice-nextstep.firebaseapp.com',
    storageBucket: 'deeplink-practice-nextstep.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqvUwNRr7mx67WX0nCHFIsvEXSISuciGI',
    appId: '1:234574443553:android:e82d85d6089478e1dd9f60',
    messagingSenderId: '234574443553',
    projectId: 'deeplink-practice-nextstep',
    storageBucket: 'deeplink-practice-nextstep.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWRKAbykR_Y1iv_tRhHKAwg8c-r-iMJ4k',
    appId: '1:234574443553:ios:ea1a526e743c0531dd9f60',
    messagingSenderId: '234574443553',
    projectId: 'deeplink-practice-nextstep',
    storageBucket: 'deeplink-practice-nextstep.appspot.com',
    iosBundleId: 'com.clean.nextstep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWRKAbykR_Y1iv_tRhHKAwg8c-r-iMJ4k',
    appId: '1:234574443553:ios:128746a81c012317dd9f60',
    messagingSenderId: '234574443553',
    projectId: 'deeplink-practice-nextstep',
    storageBucket: 'deeplink-practice-nextstep.appspot.com',
    iosBundleId: 'com.example.providerWithCleanArchitecture.RunnerTests',
  );
}
